server:
  servlet:
    session:
      timeout: 120m
  tomcat:
    uri-encoding: utf-8
  port: 10086
spring:
  thymeleaf:
    cache: false
    suffix: .html
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  aop:
    proxy-target-class: true
mybatis:
  type-aliases-package: com.joeshaw.demo.shirodemo.pojo
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mapper/**/*.xml
